### ISSUE TITLE
[commands error]docker image should be tarsdocker/tars

### ISSUE THREAD

**Issue by livyou** [TarsCloud/TarsDocker#1]
run this command：
docker run -d -it --name=tars --link mysql -e MOUNT_DATA=true -e DBIP=${your_mysql_ip} -e DBPort=3306 -e DBUser=root -e DBPassword=root@appinside -p 3000:3000 -v /data:/data tars

error:
Unable to find image 'tars:latest' locally

docker image should be tarsdocker/tars
![image](https://user-images.githubusercontent.com/3079262/50323793-5f6e6300-0516-11e9-9352-5ba46d2803fe.png)

I had run this command correctly:
 docker run -d -it --name=tars --link mysql -e MOUNT_DATA=true -e DBIP=172.17.0.2 -e DBPort=3306 -e DBUser=root -e DBPassword=root@appinside -p 3000:3000 -v /data:/data tarsdocker/tars

**Comment by jchalex** [comment]
Thanks for your advice. Have Fixed.
