### ISSUE TITLE
mac docker tars部署服务报错：pid not exist

### ISSUE THREAD

**Issue by somnmos** [TarsCloud/TarsDocker#11]
平台：mac
MySQL版本：mysql5.7
Tars镜像：tarscloud/tars
TarsNode镜像：tarscloud/tars-node

使用docker启动mysql，tars以及一个tars-node服务，在tars web管理页面部署了一个HelloGo服务，日志报错如下：

[alarm]activating, pid not exist

排查了一段时间，没能找到问题所在，麻烦大神能给点解决该问题的提示。

**Comment by segry** [comment]
我也是这个错误，详细错误如下：
java redirect stdout and stderr  to /usr/local/app/tars/app_log//TestApp/Hello/TestApp.Hello.log
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option Perm Size; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'PrintGCApplicationStoppedTime'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by segry** [comment]
用了docker dev版本和last版本，stable版本，源代码安装都一样，无法成功运行spring boot示例

**Comment by segry** [comment]
PrintGCApplicationStoppedTime 这个jvm参数在jdk9已经不能使用了@ruanshudong

**Comment by ruanshudong** [comment]
已经去掉这个参数了, 这个其实你们自己在模板里面改一下即可

**Comment by zhukaikang** [comment]
平台：mac
MySQL版本：mysql5.7
Tars镜像：tarscloud/tars
TarsNode镜像：tarscloud/tars-node

同样在web管理页面部署遇到这个错误，请问该怎么解决呢？

**Comment by silloy** [comment]
同样的错误，部署tarsjava

![image](https://user-images.githubusercontent.com/12909107/86503915-4326d400-bde5-11ea-8fb5-5444df988aa7.png)

**Comment by ruanshudong** [comment]
@zhukaikang 具体是啥错误?得给一些详细的信息
@silloy 你是如何部署的, 你java的服务运行在哪?看看tarsnode的日志,

**Comment by silloy** [comment]
https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-quick-start.html  按照这个文档一步步搞的

**Comment by ruanshudong** [comment]
看一下你部署的节点的tarsnode的日志: /usr/local/app/tars/app_log/tars/tarsnode/***.log, 确认一下你部署的机器jdk是否已经安装

**Comment by silloy** [comment]
@ruanshudong docker安装的，应该没有这个问题吧，以下是一部分错误
![image](https://user-images.githubusercontent.com/12909107/86504429-a830f880-bdea-11ea-90cb-670e619c1e8c.png)

**Comment by ruanshudong** [comment]
你的服务得部署在tars-node的docker里面, 而不是在framework的docker里面, framework的docker不带jdk环境

**Comment by silloy** [comment]
@ruanshudong 现在可以了，谢谢。node上只能部署一个app吗，client和server 应用我只能部署成功一个，关闭一个另一个就可以部署成功，这是为什么呢？端口是不冲突的，没有找到相关日志

**Comment by ruanshudong** [comment]
当然可以部署多个,  应该哪有问题, 得自己找找日志, 一个是tarsnode日志, 一个是服务自己的日志看看啥原因

**Comment by zhukaikang** [comment]
我也遇到了node上只能部署一个app的情况，启动了server就不能启动client，启动client不能启动server。请问你解决了吗 @silloy 

另外我在对 client服务进行Interface debugger时，遇到了错误
![Screen Shot 2020-07-06 at 6 06 36 PM](https://user-images.githubusercontent.com/30647817/86653791-75862c00-bfb3-11ea-987d-862f126fdc51.png)

以下是部分client 服务的日志
![Screen Shot 2020-07-06 at 6 01 59 PM](https://user-images.githubusercontent.com/30647817/86653210-04467900-bfb3-11ea-88b3-5724dd4d1f12.png)
我不太清楚为什么会连接16886端口，client服务我配置的是18602端口。

**Comment by silloy** [comment]
@zhukaikong  具体原因没有找到，我清零重来了，framework使用2.4.1，node使用tars-node:java，然后就正常了
