### ISSUE TITLE
启动tars报错，然后一直停留在服务检测

### ISSUE THREAD

**Issue by segry** [TarsCloud/TarsDocker#13]
docker run -d --net=host -e MYSQL_HOST='*****' -e MYSQL_ROOT_PASSWORD='****' \
        -eREBUILD=false -eINET=eth0 -eSLAVE=false \
        -v/data/tars:/data/tars \
        -v/etc/localtime:/etc/localtime \
        tarscloud/tars
中间有报错：
[ERROR] Process or Namespace tars-node-web not found

然后无限打印{ msg: 'pong' }
begin check server...
{ msg: 'pong' }
{ msg: 'pong' }
。。。

**Comment by segry** [comment]
@ruanshudong 大佬帮忙看看

**Comment by ruanshudong** [comment]
这是正常的 页面能打开么?

**Comment by segry** [comment]
页面可以打开，springboot示例跑不起来，在另一个issue里，这个关了
