### ISSUE TITLE
swoole版本问题

### ISSUE THREAD

**Issue by lynxcat** [TarsCloud/TarsDocker#16]
swoole已经停止对2.x的支持了，是否考虑把node环境升级到4.x呢

**Comment by franklee0817** [comment]
> swoole已经停止对2.x的支持了，是否考虑把node环境升级到4.x呢

Thank you for your advice. We've updated Swoole to the newest version 4.4.16. The new image will be pushed to the docker hub after we had it fully tested.

**Comment by franklee0817** [comment]
You can also try to use `tarsnode/php/Dockerfile` to build your own docker.
