### ISSUE TITLE
[k8s] k8s 安装外挂了本地路径，调度运行这些容器会存在问题吗？

### ISSUE THREAD

**Issue by Jamlee** [TarsCloud/TarsDocker#24]
在k8s安装时，使用了本地的磁盘路径。下面的问题会存在不：
1. 两个 tars-master 调度到同一个节点上，共享了磁盘路径，是否会存在问题呀
1. 两个 tars-node 调度到同一个节点上，共享了磁盘路径，是否会存在问题呀

**Comment by ruanshudong** [comment]
目录是不会冲突的, 因为加了一层namespace/节点host
