### ISSUE TITLE
TarsJava 应用部署到 TarsFramework 镜像上无法启动

### ISSUE THREAD

**Issue by ETZhangSX** [TarsCloud/TarsDocker#29]
提示 `[alarm] activating,pid not exist`

![16151614850403_ pic_hd](https://user-images.githubusercontent.com/20883530/110292847-cb224500-8028-11eb-9df6-60899392ac9a.jpg)

修改模板，改成 war 包后还是不行。使用的是 `tarscloud/framework` 镜像。

**Comment by ruanshudong** [comment]
文档写了, tarscloud/framework里面不包含java的运行环境啊
