### ISSUE TITLE
如何在windows上把TARS安装到Docker??

### ISSUE THREAD

**Issue by ALBERTdbg** [TarsCloud/TarsDocker#3]

**Comment by KatharineOzil** [comment]
![image](https://user-images.githubusercontent.com/13435037/65400414-a1ee0480-ddf4-11e9-9bf0-19f2658c49f7.png)
https://github.com/TarsCloud/Tars README这边说，TARS只支持在Linux操作系统上部署

**Comment by Fr1ck** [comment]
理论上可以部署在win10的linux子系统上吧

**Comment by KatharineOzil** [comment]
https://tangramor.gitlab.io/tars-docker-guide/ 这里有Windows下docker安装tars的文档～
