### ISSUE TITLE
最新版tarsnode报错

### ISSUE THREAD

**Issue by tangj1992** [TarsCloud/TarsDocker#32]
![image](https://user-images.githubusercontent.com/13653933/115192310-375e9100-a11d-11eb-9ee1-b4e1025d327f.png)

**Comment by ruanshudong** [comment]
docker用的哪个tag?

**Comment by tangj1992** [comment]
tarscloud/tars-node:java

**Comment by ruanshudong** [comment]
好的, 先看一下, 最近把docker升级支持arm, 可能还有点小问题.

**Comment by ruanshudong** [comment]
再试一试看看

**Comment by tangj1992** [comment]
![image](https://user-images.githubusercontent.com/13653933/115200234-907ef280-a126-11eb-8f3f-0a337dc41137.png)


 新的错误

**Comment by tangj1992** [comment]
可以了，谢谢
