### ISSUE TITLE
请问如何看日志？

### ISSUE THREAD

**Issue by vfan** [TarsCloud/TarsDocker#4]
只能上机器看日志么？

**Comment by ETZhangSX** [comment]
普通日志只能在机器上查看，由log节点保存到特定路径。TarsWeb可以查看上报日志，需要在业务代码中添加日志上报逻辑，例如在TarsCpp中，可以通过以下代码通过`notify`节点上报日志，日志信息会显示在`服务实时状态`中
```cpp
TarsRemoteNotify::getInstance()->report(errMsg);
```
还有可以通过`property`节点进行服务的自定义属性上报，属性监控信息会显示在`特性监控`中，相应的用法可以查看各语言开发文档中关于属性统计的用法，例如[TarsCpp属性统计用法](https://github.com/TarsCloud/TarsCpp/blob/7c54fa0cb6ceef16d2f4e615ae62778b5fd86141/docs/tars_cpp_user_guide.md#12-%E5%B1%9E%E6%80%A7%E7%BB%9F%E8%AE%A1)
